{
  "name": "pug-error",
  "description": "Standard error objects for pug",
  "version": "1.3.3",
  "repository": {
    "type": "git",
    "url": "https://github.com/pugjs/pug/tree/master/packages/pug-error"
  },
  "dist": {
    "tarball": "https://unpm.uberinternal.com/pug-error/-/pug-error-1.3.3.tgz",
    "shasum": "f342fb008752d58034c185de03602dd9ffe15fa6"
  },
  "license": "MIT",
  "directories": {},
  "_npmVersion": "lerna/3.10.8/node@v11.14.0+x64 (darwin)",
  "_npmUser": {
    "name": "forbeslindesay",
    "email": "forbes@lindesay.co.uk"
  },
  "_id": "pug-error@1.3.3",
  "gitHead": "1bdf628a70fda7a0d840c52f3abce54b1c6b0130",
  "_hasShrinkwrap": false,
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/pug-error_1.3.3_1560851095122_0.6161359800057267"
  },
  "_nodeVersion": "11.14.0",
  "_shasum": "f342fb008752d58034c185de03602dd9ffe15fa6",
  "_resolved": "https://unpm.uberinternal.com/pug-error/-/pug-error-1.3.3.tgz",
  "_from": "pug-error@>=1.3.3 <2.0.0",
  "readme": "ERROR: No README data found!",
  "scripts": {}
}
